services:
  app: # app 이하 코드를 도커 이미지 빌드 후 추가!
    image: rebuild-app:local
    container_name: rebuild-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=s8Kf9!xP2zLq#0Wm@R4tV7nB3uHQp1YcE5jD8rT6kF!Zg9
    depends_on:
      - rebuild-mysql
    restart: unless-stopped

  rebuild-mysql:     # 팀/프로젝트 이름을 접두사로 붙여 팀원이 여러 도커 띄워도 충돌이 안 나도록!
    image: mysql:8.0.43
    container_name: rebuild-mysql-dev  # 프로젝트-서비스-환경 -> 협업 시 직관적임
    environment:
      MYSQL_ROOT_PASSWORD: rebuild_root
      MYSQL_DATABASE: rebuild_db
      MYSQL_USER: rebuild
      MYSQL_PASSWORD: rebuild_pw
      TZ: Asia/Seoul
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3309:3306"
    volumes:
      - ./_vol/mysql:/var/lib/mysql
