spring:
  datasource:
    url: jdbc:mysql://localhost:3309/rebuild_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: rebuild
    password: rebuild_pw
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true # SQL을 예쁘게 줄바꿈해서 보여줌
server.port: 8080