services:
  app:
    image: leeym1/rebuild:latest
    container_name: rebuild-app
    environment:
      JWT_SECRET: "s8Kf9!xP2zLq#0Wm@R4tV7nB3uHQp1YcE5jD8rT6kF!Zg9"
    env_file:
      - .env.prod     # 실제 서버에서 제공
    ports:
      - "80:8080"
    depends_on:
      - rebuild-mysql
    restart: unless-stopped

  rebuild-mysql:
    image: mysql:8.0.43
    container_name: rebuild-mysql
    env_file:
      - .env.prod
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - ./_vol/mysql:/var/lib/mysql
    restart: unless-stopped